# Generated by Django 3.2.12 on 2022-09-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='oid',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='原id'),
            preserve_default=False,
        ),
    ]
