# Generated by Django 3.2.12 on 2022-09-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_oid'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='用户id')),
                ('rentalId', models.IntegerField(verbose_name='房源id')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '房源浏览记录',
                'verbose_name_plural': '房源浏览记录',
                'db_table': 'view_history',
            },
        ),
    ]
