# Generated by Django 3.2.15 on 2024-03-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '公告管理',
                'verbose_name_plural': '公告管理',
                'db_table': 'notify',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('price_text', models.CharField(max_length=255, verbose_name='租金')),
                ('structure', models.CharField(max_length=255, verbose_name='户型')),
                ('tags', models.TextField(verbose_name='标签,逗号分隔')),
                ('area_text', models.CharField(max_length=255, verbose_name='面积')),
                ('city', models.CharField(max_length=255, verbose_name='所在城市')),
                ('location', models.CharField(max_length=255, verbose_name='位置')),
                ('floor', models.IntegerField(null=True, verbose_name='楼层')),
            ],
            options={
                'verbose_name': '预定记录',
                'verbose_name_plural': '预定记录',
                'db_table': 'reserve',
            },
        ),
    ]
