# Generated by Django 3.2.15 on 2024-03-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_notify_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='userId',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
    ]
